### ISSUE TITLE
A Decomposable Attention Model for Natural Language Inference

### ISSUE THREAD

**Issue by yunhenk** [NTMC-Community/awaresome-neural-models-for-semantic-match#26]
Here is an important work for NLI task, which can be added:
A Decomposable Attention Model for Natural Language Inference [EMNLP 2016, by Google]
[open code](https://github.com/HsiaoYetGun/Decomposable-Attention)
please consider it

**Comment by bwanglzu** [comment]
hi @yunhenk would you like to send a pull request?

**Comment by yunhenk** [comment]
@bwanglzu pull request sent. One problem found: the title of this repository is misspelled : Awesome <-Awaresome. The same spelling problem in README.md is fixed in the pull request.

**Comment by faneshion** [comment]
Hi @yunhenk , I am glad to have this paper included in the list. Could you please implement this model into MatchZoo repo?

**Comment by yunhenk** [comment]
@faneshion OK, I'll give it a try.
